# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - Bebac-Mobile

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.18.0' 
          
      - name: Install npm
        run: npm install 
      - name: Install Angular CLI
        run: npm install @angular/cli
      - name: Install Ionic CLI
        run: npm install  @ionic/cli
      - name: Build
        run: |
         npx ionic build --prod
      - name: Copy .well-known directory
        run: |
          cp .well-known/assetlinks.json www/ |
          cp .well-known/apple-developer-merchantid-domain-association www/ |
           cp .well-known/apple-app-site-association www/
      - name: Copy staticwebapp.config.json to www folder
        run: |
         cp staticwebapp.config.json www/staticwebapp.config.json 
      

      - name: Zip artifact for deployment
        run:  zip -r release.zip ./www/*

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D2C03087D8DE478FA2428B8BCF3B240C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_068F52FF8ABD4062B601864D2A6ED4F5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FB0E9F0949E0464381DBF3DF90D860C9 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'Bebac-Mobile'
          slot-name: 'Production'
          package: ./www
          
